document.addEventListener('DOMContentLoaded',()=>{loadInit();});function loadInit(){function ChunkArray(array,chunk){const results=[];while(array.length){results.push(array.splice(0,chunk));}
return results;}
function WCHRequest(idsPackage){const xhr=new XMLHttpRequest();const reqBody=JSON.stringify({fields:['id','elements'],ids:idsPackage,});const APIUrl='https://content-us-7.content-cms.com/api/1285e1d2-5151-4eab-9da2-775291879cb9/delivery/v1/content/bulk_retrieve';xhr.open('POST',APIUrl,true);xhr.setRequestHeader('Content-Type','application/json');xhr.onload=function(data){if(this.status===200){const responseData=JSON.parse(this.responseText);for(let dataIndex=0;dataIndex<responseData.length;dataIndex+=1){const dataElement=responseData[dataIndex];const imageDomain='https://content-us-7.content-cms.com';let src;for(let nodeIndex=0;nodeIndex<imageNodes.length;nodeIndex+=1){const imageNode=imageNodes[nodeIndex];if(dataElement.id===imageNode.dataset.id){if(imageNode.dataset.imageType==='r'){if(imageNode.dataset.imageSize==='s'){src=dataElement.elements.images.values[0].renditions.small_r.url;}else if(imageNode.dataset.imageSize==='m'){src=dataElement.elements.images.values[0].renditions.medium_r.url;}else if(imageNode.dataset.imageSize==='l'){src=dataElement.elements.images.values[0].renditions.large_r.url;}else{src=dataElement.elements.images.values[0].renditions.default.url;}}else if(imageNode.dataset.imageType==='c'){if(imageNode.dataset.imageSize==='s'){src=dataElement.elements.images.values[0].renditions.small_c.url;}else if(imageNode.dataset.imageSize==='m'){src=dataElement.elements.images.values[0].renditions.medium_c.url;}else if(imageNode.dataset.imageSize==='l'){src=dataElement.elements.images.values[0].renditions.long_c.url;}else{src=dataElement.elements.images.values[0].renditions.default.url;}}else{src=dataElement.elements.images.values[0].renditions.default.url;}
imageNode.dataset.src=imageDomain+src;}}}
return responseData;}
console.log('Error',xhr);};xhr.send(reqBody);}
function getImageData(array){for(let i=0;i<array.length;i+=1){const element=array[i];const resultados=WCHRequest(element);}}
const imageNodes=document.getElementsByClassName('wch-image');const imageNodesToArray=[];for(let nodeIndex=0;nodeIndex<imageNodes.length;nodeIndex+=1){const element=imageNodes[nodeIndex];imageNodesToArray.push(element);}
const imagesNodesIds=[];for(let nodeIdIndex=0;nodeIdIndex<imageNodesToArray.length;nodeIdIndex+=1){const nodeElement=imageNodesToArray[nodeIdIndex];const idElement=nodeElement.dataset.id;const httpsRegEx=/https:/g;const varRegEx=/{img}/g;const whiteSpacesRegEx=/\s+/g;if(httpsRegEx.test(idElement)){nodeElement.dataset.src=idElement;}else if(varRegEx.test(idElement)){console.log(`Bad value from:${nodeElement.outerHTML}`);}else if(whiteSpacesRegEx.test(idElement)){let idWithoutSpaces=idElement.replace(whiteSpacesRegEx,"");imagesNodesIds.push(idWithoutSpaces);nodeElement.setAttribute('data-id',idWithoutSpaces);}else if(idElement!==undefined){imagesNodesIds.push(idElement);}}
const chunkSize=25;if(imagesNodesIds.length>0){const imageIdsPackage=ChunkArray(imagesNodesIds,chunkSize);getImageData(imageIdsPackage);}}
window.addEventListener('load',()=>{setInit();});function setInit(){const imageElements=document.querySelectorAll('.wch-image');const imgOptions={threshold:0.25,rootMargin:'0px 0px 100px 0px',};const imgObserver=new IntersectionObserver((entries,imgObserver)=>{entries.forEach(entry=>{if(!entry.isIntersecting){return;}
const{src,alt,title}=entry.target.dataset;if(entry.target.tagName==='IMG'){src?(entry.target.src=src):'';alt?(entry.target.alt=alt):'';title?(entry.target.title=title):'';entry.target.src!==''?imgObserver.unobserve(entry.target):'';}else if(entry.target.tagName==='SOURCE'){entry.target.srcset=entry.target.dataset.src;imgObserver.unobserve(entry.target);}else if(entry.target.tagName==='IFRAME'){entry.target.src=entry.target.dataset.src;imgObserver.unobserve(entry.target);}else{src?(entry.target.style.backgroundImage=`url(${src})`):'';if(entry.target.style.backgroundImage!==''){imgObserver.unobserve(entry.target);}}});},imgOptions);imageElements.forEach(imageElement=>{imgObserver.observe(imageElement);});}